import {API_URL} from '@env';

export const URLS = {
  login: '/users/login',
  logout: '/users/logout',
  resetPassword: '/users/reset-password',
  createUser: '/users',
  resetPin: '/users/reset-pin',
  bioLogin: '/auth/bio-login',
  bioRegister: '/auth/register-bio-login',
  bioRegisterFromSettings: '/auth/register-bio',
  bioDelete: '/auth/delete-bio-login',
  refreshToken: '/auth/token/refresh',
  verifyPhone: '/users/pre-signup-otp',
  verifyOtp: '/users/verify-otp',
  forgotPassword: 'users/forgot-password-change',
  sendOtpOnUserPhone: '/users/forgot-password-otp',
  verifyLoginUserOtp: '/users/verify-mobile-otp',
  verifyOtpForChangeNumber: 'users/change-phone-otp',
  changeUserPhoneNum: 'users/phone-verify-otp',
  getFeeWithAmount: 'fee/usdc-exchange',
  initiateBVN: '/feni/bvn/initiate',
  verifyBVN: '/feni/bvn/verify',
  fetchBVN: '/feni/bvn/fetch',
  createNGNWallet: '/wallets/ng-wallet',
  getKycStatus: '/users/kyc-status',
  getKycUrl: '/users/create-kyc-url',
  getUserInfo: '/users/me',
  getUserTransactionControl: '/transactions/controls',
  getWallets: '/wallets/my-wallet',
  getHTMLPages: '/metadata/html-pages',
  getWalletBalance: '/wallets/info',
  createBUSorIND: '/users/individual_and_business',
  uploadProfileImage: '/users/profile-image',
  getNGNBankList: '/feni/transfer/getbanks',
  getAccount: '/feni/transfer/getaccount',
  getWalletsTransaction: '/wallets/transactions',
  getWalletsTransfer: '/wallets/trades',
  ngnExternalTransfer: '/transactions/ng/external-transfer',
  ngnIxternalTransfer: '/transactions/ng/internal-transfer',
  getUserList: `/users/search`,
  verifyPin: `/users/verify-pin`,
  exchangeMoney: `/transactions/us/exchange`,
  externalSupportURL: 'https://support.krillpay.com/support/home',
  bookTransfer: '/transactions/us/book-transfer',
  feildAvailable: '/users/is-field-available',
  getCountriesList: '/metadata/countries',
  getStatesFromCountry: '/metadata/states',
  getCitiesFromState: '/metadata/cities',
  plaidWorkflow: '/users/workflow',
  plaidLinkToken: '/users/plaid-link-token',
  externalBankList: '/users/external-bank-accounts',
  addExternalBank: '/cybrid/external-bank-accounts',
  verifyExternalBank: '/cybrid/verify-external-bank-accounts',
  addMoneyFromExternalBank: '/transactions/external-bank/cash-in',
  addMoneyToExternlaBank: '/transactions/external-bank/cash-out',
  getChargeFromAmount: '/feni/transaction/charge',
  getBankBalance: '/cybrid/external-bank-accounts/balances',
  getBookTransferCharge: '/transactions/us/get-book-quote',
  getYellowChannels: '/yellow/channels',
  getYellowNetworks: '/yellow/networks',
  getExchangeRates: '/yellow/rates',
  initiateYellowTranscation: '/yellow/transfer',
  getBankAccountName: '/yellow/account-name',
  deleteExternalBank: '/users/external-bank-accounts',
  krillTag: '/wallets/qr-code',
};

// export const BASE_URL = 'https://apistaging.krillpay.com/api';
export const BASE_URL = 'https://apiprod.krillpay.com/api';
// export const BASE_URL = API_URL;
