export const AUTH_NAVIGATOR = {
  splash: 'SplashScreen',
  login: 'LoginScreen',
  enableBioLogin: 'EnableBioLoginScreen',
  confirmPin: 'ConfirmPinScreen',
  signupType: 'SignupTypeScreen',
  signupStart: 'SignupStartScreen',
  signup: 'SignupScreen',
  verifyAuthOtp: 'VerifyAuthOTPScreen',
  accountDetails: 'AccountDetailsScreen',
  createPin: 'CreatePinAccountScreen',
  signupSuccess: 'SignUpSuccessScreen',
  forgotPassword: 'ForgotPassword',
  forgotOTP: 'ForgotOTP',
  ressetPass: 'ResetPass',
};

export const BOTTOM_TAB_NAVIGATOR = {
  home: 'bottomTabHome',
  sendMoney: 'sendMoney',
  recieveMoney: 'recieveMoney',
  wallet: 'wallets',
  profile: 'profile',
};

export const DRAWER_NAVIGATOR = {
  home: 'home',
  QRCode: 'QRCode',
  KYCDetails: 'KYCDetails',
  TransactionHistory: 'TransactionHistory',
  CreateIndividualAccount: 'CreateIndividualAccount',
  CreateBusinessAccount: 'CreateBusinessAccount',
  Dispute: 'Dispute',
  FAQ: 'FAQ',
  ContactUs: 'ContactUs',
  Setting: 'Settings',
};

export const MAIN_NAVIGATOR = {
  Drawer: 'Drawer',
  Auth: 'Auth',
  SendMoney: 'TransferMoney',
  Review: 'ReviewTransfer',
  Pin: 'PIN',
  ResetPin: 'ResetPin',
  KYCVerfication: 'KYCVerification',
  ConfirmResetPin: 'ConfirmResetPin',
  TransactionComplete: 'transactionComplete',
  TransactionFailure: 'transactionFailure',
  Deposit: 'Deposit',
  PlaidView: 'PlaidViewScreen',
  Exchange: 'ExchangeMoney',
  Recipient: 'Recipient',
  UserCountryScreen: 'UserCountryScreen',
  YellowCardFlowScreen: 'YellowCardFlowScreen',
  BankTransferScreen: 'BankTransferScreen',
  profileScreen: 'ProfileScreen',
  securityScreen: 'SecurityScreen',
  Reset: 'ResetScreen',
  VerifyOTP: 'VerifyOTP',
  CurrentPin: 'CurrentPinScreen',
  PolicyScreen: 'PolicyScreen',
  ExternalBankTransferScreen: 'ExternalBankTransferScreen',
};
